export interface CreateEmployeeDto {
  name: string;
  position: string;
  department: string;
  internal_code?: string; // Optional as it might be auto-generated
  qr_code?: string; // Optional as it's generated by the database
  created_at?: string; // Optional as it's handled by the database
}
